name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build
    runs-on: macos-10.14
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2 
  
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.2
      with:
        node-version: 10.0.0
  
    - name: Get dependencies
      run: |
        go get -v github.com/goplusjs/gopherjs
        go list github.com/goplusjs/gopherjs
        cd $HOME/go/src/github.com/goplusjs/gopherjs
        go install -v
        npm install # Install our (dev) dependencies from package.json.
        cd node-syscall && ../node_modules/node-gyp/bin/node-gyp.js rebuild rebuild && mkdir -p ~/.node_libraries && cp build/Release/syscall.node ~/.node_libraries/syscall.node
    - name: Test
      run: |
        cd $HOME/go/src/github.com/goplusjs/gopherjs
        ulimit -s 10000 && gopherjs test --minify -v --short $(go list std | grep -v -x -f .std_test_pkg_exclusions)
  
