name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build
    runs-on: macos-10.14
    steps:

    - name: Set up Go 1.12
      uses: actions/setup-go@v2
      with:
        go-version: 1.12.17

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2 
      with:
        path: /Users/runner/go
  
    - name: Test and Run
      run: |
          pwd
